<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-8B5VFCJA" ignored="0" name="Default test" tests="9" failures="1" timestamp="13 Aug 2021 10:19:35 GMT" time="64.014" errors="0">
  <testcase name="verifyFlashMovieDemoLinkTest" time="1.586" classname="com.Guru99.qa.testcases.HomePageTest"/>
  <testcase name="verifyHomePageTitleTest" time="0.011" classname="com.Guru99.qa.testcases.HomePageTest"/>
  <testcase name="verifyLoginButtonTest" time="1.335" classname="com.Guru99.qa.testcases.HomePageTest"/>
  <testcase name="verifyLogoTest" time="3.077" classname="com.Guru99.qa.testcases.HomePageTest"/>
  <testcase name="verifyPageNameTest" time="0.092" classname="com.Guru99.qa.testcases.HomePageTest"/>
  <testcase name="verifyRadioDemoLinkTest" time="1.46" classname="com.Guru99.qa.testcases.HomePageTest"/>
  <testcase name="verifyResetButtonTest" time="0.454" classname="com.Guru99.qa.testcases.HomePageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [ ] but found []">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [ ] but found []
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
	at com.Guru99.qa.testcases.HomePageTest.verifyResetButtonTest(HomePageTest.java:78)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:39)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:421)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verifyResetButtonTest -->
  <testcase name="verifySeleniumLinkTest" time="0.246" classname="com.Guru99.qa.testcases.HomePageTest"/>
  <testcase name="verifySignupLinkTest" time="1.888" classname="com.Guru99.qa.testcases.HomePageTest"/>
</testsuite> <!-- Default test -->
